Wagtail 3.0 Support
torchbox/wagtail-footnotes pull request #29
Opened 2022-06-03 09:01 UTC by BrianXu20

[Ticket
](https://projects.torchbox.com/projects/support-team/tickets/491)

Make the current package support Wagtail 3.0. 

- Drop Django 2.2 (EOL)
- Drop Python 3.6 (EOL)
- Drop Wagtail <2.15 (EOL)
- Add Wagtail 3.0 support

2022-06-07 13:54 UTC, nickmoreton requested changes
A couple of small suggestions.

2022-06-08 02:17 UTC, BrianXu20 commented on setup.cfg
> +    Django>=3.2, <5.0
I think Wagtail 3.0 supports Django4.0, and you can't install wagtail <3.0 with Django4.0 that's why I did this. However, I think we can limit it to Django3 as the priority is to support Wagtail3.0

2022-06-08 07:58 UTC, nickmoreton approved these changes
LGTM! Thanks Brian

2022-06-09 06:02 UTC, BrianXu20 commented
Hi @zerolab , 
Can we have this merge in and have a release? 
Thank you

2022-06-23 16:10 UTC, kevinhowbrook approved these changes
Thanks @BrianXu20 I've updated this with master and bumped the version for a new release

2022-06-23 16:15 UTC, merged

2022-06-23 22:46 UTC, jsma commented
I'm not sure I understand the reasoning and decision above https://github.com/torchbox/wagtail-footnotes/pull/29#discussion_r891258536

If someone is using this package with a project that is pinned to Wagtail 2.15, Wagtail itself will constrain the version of Django installed (assuming the project hasn't also pinned the version of Django). But by restricting Django to <4.0 here, this prevents projects from running Wagtail 3 & Django 4.0.x when using wagtail-footnotes.

E.g. with requirements.txt:
```
wagtail==3.0.1
django==4.0.5
# Install from Github since 0.8.0 is not on PyPI yet
-e git+https://github.com/torchbox/wagtail-footnotes@0.8.0#egg=wagtail-footnotes
```

```
pip install -r requirements.txt
...snip...
ERROR: Cannot install -r requirements.txt (line 1), -r requirements.txt (line 3) and django==4.0.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested django==4.0.5
    wagtail 3.0.1 depends on Django<4.1 and >=3.2
    wagtail-footnotes 0.8.0 depends on Django<4.0 and >=3.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```