Wagtail 6.0
torchbox/wagtail-footnotes pull request #66
Opened 2024-02-20 08:07 UTC by katdom13

[Support Ticket](https://torchbox.monday.com/boards/1124794299/pulses/1396934613)
[Internal PR with Dan's initial comments](https://github.com/torchbox-forks/wagtail-footnotes/pull/2)

## [Wagtail 6.0 release notes](https://docs.wagtail.org/en/stable/releases/6.0.html)

### Summary of changes

- Added Wagtail 6.0 compatibility
- Added tests for Django 5.0
- Added tests for Python 3.12

2024-02-20 08:10 UTC, katdom13 commented on wagtail_footnotes/widgets.py
> +            return mark_safe(widget_html)  # noqa: S308
This section was copied from Wagtail's `WidgetWithScript`:
https://github.com/wagtail/wagtail/blob/main/wagtail/utils/widgets.py#L27

2024-05-16 18:03 UTC, zerolab requested changes
It is shaping up well. A few tweaks needed

2024-05-16 18:03 UTC, zerolab commented on CHANGELOG.md
> +- Add compatibility tests for Wagtail 6.0 and Python 3.12 @katdom13
```suggestion
- Drop support for Wagtail < 5.2 @katdom13
- Add support for Wagtail 6.0/6.1, Django 5.0 and Python 3.12 @katdom13
```

2024-05-17 03:48 UTC, katdom13 commented
@zerolab ,
Could you please have a quick look at the latest changes?
Thank you!

2024-05-17 03:48 UTC, katdom13 commented on tox.ini
> +    wagtail6.0: wagtail>=6.0,<6.1
Hi @zerolab ,
Updated here: https://github.com/torchbox/wagtail-footnotes/pull/66/commits/8219a7f7f0e290b72e80069315c13f7ef8e236ad

2024-05-17 03:48 UTC, katdom13 commented on wagtail_footnotes/static/footnotes/js/read-only-uuid-controller.js
> +
https://github.com/torchbox/wagtail-footnotes/pull/66/commits/b374a5afbf3f325be6bb1bf268794feb2bfcb681

2024-05-17 03:48 UTC, katdom13 commented on wagtail_footnotes/widgets.py
> +if WAGTAIL_VERSION and WAGTAIL_VERSION >= (6, 0):
https://github.com/torchbox/wagtail-footnotes/pull/66/commits/1f4f21b4af2a926e5d19314758a8ea143e0355f0

2024-05-17 03:48 UTC, katdom13 commented on CHANGELOG.md
> +- Add compatibility tests for Wagtail 6.0 and Python 3.12 @katdom13
https://github.com/torchbox/wagtail-footnotes/pull/66/commits/3dbc60a51883cdd00eb1ea08ca7e92c0a2182638

2024-05-17 08:24 UTC, zerolab commented on tox.ini
>      coverage[toml]>=7.2,<8.0
```suggestion
```

should not be needed since you added `extras = testing`

2024-05-17 13:16 UTC, zerolab approved these changes

2024-05-17 13:17 UTC, merged

2024-05-17 13:17 UTC, zerolab commented
Thank you @katdom13